/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InteractionService } from "../interaction.service";
import { InteractionCreateInput } from "./InteractionCreateInput";
import { Interaction } from "./Interaction";
import { InteractionFindManyArgs } from "./InteractionFindManyArgs";
import { InteractionWhereUniqueInput } from "./InteractionWhereUniqueInput";
import { InteractionUpdateInput } from "./InteractionUpdateInput";
import { VoiceRecordingFindManyArgs } from "../../voiceRecording/base/VoiceRecordingFindManyArgs";
import { VoiceRecording } from "../../voiceRecording/base/VoiceRecording";
import { VoiceRecordingWhereUniqueInput } from "../../voiceRecording/base/VoiceRecordingWhereUniqueInput";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { MessageWhereUniqueInput } from "../../message/base/MessageWhereUniqueInput";

export class InteractionControllerBase {
  constructor(protected readonly service: InteractionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Interaction })
  @swagger.ApiBody({
    type: InteractionCreateInput,
  })
  async createInteraction(
    @common.Body() data: InteractionCreateInput
  ): Promise<Interaction> {
    return await this.service.createInteraction({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        interactionType: true,
        timestamp: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Interaction] })
  @ApiNestedQuery(InteractionFindManyArgs)
  async interactions(@common.Req() request: Request): Promise<Interaction[]> {
    const args = plainToClass(InteractionFindManyArgs, request.query);
    return this.service.interactions({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        interactionType: true,
        timestamp: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Interaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async interaction(
    @common.Param() params: InteractionWhereUniqueInput
  ): Promise<Interaction | null> {
    const result = await this.service.interaction({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        interactionType: true,
        timestamp: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Interaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: InteractionUpdateInput,
  })
  async updateInteraction(
    @common.Param() params: InteractionWhereUniqueInput,
    @common.Body() data: InteractionUpdateInput
  ): Promise<Interaction | null> {
    try {
      return await this.service.updateInteraction({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          interactionType: true,
          timestamp: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Interaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteInteraction(
    @common.Param() params: InteractionWhereUniqueInput
  ): Promise<Interaction | null> {
    try {
      return await this.service.deleteInteraction({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          interactionType: true,
          timestamp: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/voiceRecordings")
  @ApiNestedQuery(VoiceRecordingFindManyArgs)
  async findVoiceRecordings(
    @common.Req() request: Request,
    @common.Param() params: InteractionWhereUniqueInput
  ): Promise<VoiceRecording[]> {
    const query = plainToClass(VoiceRecordingFindManyArgs, request.query);
    const results = await this.service.findVoiceRecordings(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        fileUrl: true,
        duration: true,

        interaction: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/voiceRecordings")
  async connectVoiceRecordings(
    @common.Param() params: InteractionWhereUniqueInput,
    @common.Body() body: VoiceRecordingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      voiceRecordings: {
        connect: body,
      },
    };
    await this.service.updateInteraction({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/voiceRecordings")
  async updateVoiceRecordings(
    @common.Param() params: InteractionWhereUniqueInput,
    @common.Body() body: VoiceRecordingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      voiceRecordings: {
        set: body,
      },
    };
    await this.service.updateInteraction({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/voiceRecordings")
  async disconnectVoiceRecordings(
    @common.Param() params: InteractionWhereUniqueInput,
    @common.Body() body: VoiceRecordingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      voiceRecordings: {
        disconnect: body,
      },
    };
    await this.service.updateInteraction({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/messages")
  @ApiNestedQuery(MessageFindManyArgs)
  async findMessages(
    @common.Req() request: Request,
    @common.Param() params: InteractionWhereUniqueInput
  ): Promise<Message[]> {
    const query = plainToClass(MessageFindManyArgs, request.query);
    const results = await this.service.findMessages(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        content: true,
        senderId: true,

        interaction: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/messages")
  async connectMessages(
    @common.Param() params: InteractionWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        connect: body,
      },
    };
    await this.service.updateInteraction({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/messages")
  async updateMessages(
    @common.Param() params: InteractionWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        set: body,
      },
    };
    await this.service.updateInteraction({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/messages")
  async disconnectMessages(
    @common.Param() params: InteractionWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        disconnect: body,
      },
    };
    await this.service.updateInteraction({
      where: params,
      data,
      select: { id: true },
    });
  }
}
