/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VoiceRecordingService } from "../voiceRecording.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VoiceRecordingCreateInput } from "./VoiceRecordingCreateInput";
import { VoiceRecording } from "./VoiceRecording";
import { VoiceRecordingFindManyArgs } from "./VoiceRecordingFindManyArgs";
import { VoiceRecordingWhereUniqueInput } from "./VoiceRecordingWhereUniqueInput";
import { VoiceRecordingUpdateInput } from "./VoiceRecordingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VoiceRecordingControllerBase {
  constructor(
    protected readonly service: VoiceRecordingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VoiceRecording })
  @nestAccessControl.UseRoles({
    resource: "VoiceRecording",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: VoiceRecordingCreateInput,
  })
  async createVoiceRecording(
    @common.Body() data: VoiceRecordingCreateInput
  ): Promise<VoiceRecording> {
    return await this.service.createVoiceRecording({
      data: {
        ...data,

        interaction: data.interaction
          ? {
              connect: data.interaction,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        fileUrl: true,
        duration: true,

        interaction: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [VoiceRecording] })
  @ApiNestedQuery(VoiceRecordingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VoiceRecording",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async voiceRecordings(
    @common.Req() request: Request
  ): Promise<VoiceRecording[]> {
    const args = plainToClass(VoiceRecordingFindManyArgs, request.query);
    return this.service.voiceRecordings({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        fileUrl: true,
        duration: true,

        interaction: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VoiceRecording })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VoiceRecording",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async voiceRecording(
    @common.Param() params: VoiceRecordingWhereUniqueInput
  ): Promise<VoiceRecording | null> {
    const result = await this.service.voiceRecording({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        fileUrl: true,
        duration: true,

        interaction: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VoiceRecording })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VoiceRecording",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: VoiceRecordingUpdateInput,
  })
  async updateVoiceRecording(
    @common.Param() params: VoiceRecordingWhereUniqueInput,
    @common.Body() data: VoiceRecordingUpdateInput
  ): Promise<VoiceRecording | null> {
    try {
      return await this.service.updateVoiceRecording({
        where: params,
        data: {
          ...data,

          interaction: data.interaction
            ? {
                connect: data.interaction,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          fileUrl: true,
          duration: true,

          interaction: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VoiceRecording })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VoiceRecording",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVoiceRecording(
    @common.Param() params: VoiceRecordingWhereUniqueInput
  ): Promise<VoiceRecording | null> {
    try {
      return await this.service.deleteVoiceRecording({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          fileUrl: true,
          duration: true,

          interaction: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
