/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { JobPositionService } from "../jobPosition.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { JobPositionCreateInput } from "./JobPositionCreateInput";
import { JobPosition } from "./JobPosition";
import { JobPositionFindManyArgs } from "./JobPositionFindManyArgs";
import { JobPositionWhereUniqueInput } from "./JobPositionWhereUniqueInput";
import { JobPositionUpdateInput } from "./JobPositionUpdateInput";
import { InterviewFindManyArgs } from "../../interview/base/InterviewFindManyArgs";
import { Interview } from "../../interview/base/Interview";
import { InterviewWhereUniqueInput } from "../../interview/base/InterviewWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class JobPositionControllerBase {
  constructor(
    protected readonly service: JobPositionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: JobPosition })
  @nestAccessControl.UseRoles({
    resource: "JobPosition",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: JobPositionCreateInput,
  })
  async createJobPosition(
    @common.Body() data: JobPositionCreateInput
  ): Promise<JobPosition> {
    return await this.service.createJobPosition({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        status: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [JobPosition] })
  @ApiNestedQuery(JobPositionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "JobPosition",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async jobPositions(@common.Req() request: Request): Promise<JobPosition[]> {
    const args = plainToClass(JobPositionFindManyArgs, request.query);
    return this.service.jobPositions({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        status: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: JobPosition })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobPosition",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async jobPosition(
    @common.Param() params: JobPositionWhereUniqueInput
  ): Promise<JobPosition | null> {
    const result = await this.service.jobPosition({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        status: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: JobPosition })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobPosition",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: JobPositionUpdateInput,
  })
  async updateJobPosition(
    @common.Param() params: JobPositionWhereUniqueInput,
    @common.Body() data: JobPositionUpdateInput
  ): Promise<JobPosition | null> {
    try {
      return await this.service.updateJobPosition({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          status: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: JobPosition })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobPosition",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteJobPosition(
    @common.Param() params: JobPositionWhereUniqueInput
  ): Promise<JobPosition | null> {
    try {
      return await this.service.deleteJobPosition({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          status: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/interviews")
  @ApiNestedQuery(InterviewFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Interview",
    action: "read",
    possession: "any",
  })
  async findInterviews(
    @common.Req() request: Request,
    @common.Param() params: JobPositionWhereUniqueInput
  ): Promise<Interview[]> {
    const query = plainToClass(InterviewFindManyArgs, request.query);
    const results = await this.service.findInterviews(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        date: true,
        feedback: true,
        interviewer: true,
        candidate: true,

        jobPosition: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/interviews")
  @nestAccessControl.UseRoles({
    resource: "JobPosition",
    action: "update",
    possession: "any",
  })
  async connectInterviews(
    @common.Param() params: JobPositionWhereUniqueInput,
    @common.Body() body: InterviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      interviews: {
        connect: body,
      },
    };
    await this.service.updateJobPosition({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/interviews")
  @nestAccessControl.UseRoles({
    resource: "JobPosition",
    action: "update",
    possession: "any",
  })
  async updateInterviews(
    @common.Param() params: JobPositionWhereUniqueInput,
    @common.Body() body: InterviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      interviews: {
        set: body,
      },
    };
    await this.service.updateJobPosition({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/interviews")
  @nestAccessControl.UseRoles({
    resource: "JobPosition",
    action: "update",
    possession: "any",
  })
  async disconnectInterviews(
    @common.Param() params: JobPositionWhereUniqueInput,
    @common.Body() body: InterviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      interviews: {
        disconnect: body,
      },
    };
    await this.service.updateJobPosition({
      where: params,
      data,
      select: { id: true },
    });
  }
}
