/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CandidateApplication } from "./CandidateApplication";
import { CandidateApplicationCountArgs } from "./CandidateApplicationCountArgs";
import { CandidateApplicationFindManyArgs } from "./CandidateApplicationFindManyArgs";
import { CandidateApplicationFindUniqueArgs } from "./CandidateApplicationFindUniqueArgs";
import { CreateCandidateApplicationArgs } from "./CreateCandidateApplicationArgs";
import { UpdateCandidateApplicationArgs } from "./UpdateCandidateApplicationArgs";
import { DeleteCandidateApplicationArgs } from "./DeleteCandidateApplicationArgs";
import { CandidateApplicationService } from "../candidateApplication.service";
@graphql.Resolver(() => CandidateApplication)
export class CandidateApplicationResolverBase {
  constructor(protected readonly service: CandidateApplicationService) {}

  async _candidateApplicationsMeta(
    @graphql.Args() args: CandidateApplicationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CandidateApplication])
  async candidateApplications(
    @graphql.Args() args: CandidateApplicationFindManyArgs
  ): Promise<CandidateApplication[]> {
    return this.service.candidateApplications(args);
  }

  @graphql.Query(() => CandidateApplication, { nullable: true })
  async candidateApplication(
    @graphql.Args() args: CandidateApplicationFindUniqueArgs
  ): Promise<CandidateApplication | null> {
    const result = await this.service.candidateApplication(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CandidateApplication)
  async createCandidateApplication(
    @graphql.Args() args: CreateCandidateApplicationArgs
  ): Promise<CandidateApplication> {
    return await this.service.createCandidateApplication({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => CandidateApplication)
  async updateCandidateApplication(
    @graphql.Args() args: UpdateCandidateApplicationArgs
  ): Promise<CandidateApplication | null> {
    try {
      return await this.service.updateCandidateApplication({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CandidateApplication)
  async deleteCandidateApplication(
    @graphql.Args() args: DeleteCandidateApplicationArgs
  ): Promise<CandidateApplication | null> {
    try {
      return await this.service.deleteCandidateApplication(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
